#!/usr/bin/env python3
"""IMU gravity calibration for forward-tilted Livox mount.

Dog must stand still on flat ground. Uses /livox/imu (preferred) or
/imu/data_raw. Gravity in the IMU frame gives "up"; recover pitch_down/roll
(positive pitch_down = looking at ground).

Optionally RANSAC-fit /livox/lidar (or /lio/cloud_world) for cross-check.

Writes config/lidar_extrinsic.yaml. Launch values:
  genisom / lio_tf: lidar_pitch = -pitch_down

Example:
  source /opt/ros/humble/setup.bash && source ~/robot_ws/install/setup.bash
  python3 ~/robot_ws/scripts/calib_lidar_imu_gravity.py --seconds 8 --apply
"""
from __future__ import annotations

import argparse
import math
import os
import sys
import time

import numpy as np

try:
    import rclpy
    from rclpy.node import Node
    from rclpy.qos import qos_profile_sensor_data
    from sensor_msgs.msg import Imu, PointCloud2
    import struct
except Exception as e:
    print('Need ROS2 Python deps:', e)
    sys.exit(1)

OUT_DEFAULT = '/home/linaro/robot_ws/config/lidar_extrinsic.yaml'


def unpack_xyz(msg: PointCloud2, stride=3, max_n=25000):
    fmap = {f.name: f for f in msg.fields}
    if not all(k in fmap for k in ('x', 'y', 'z')):
        return np.zeros((0, 3))
    ox, oy, oz = fmap['x'].offset, fmap['y'].offset, fmap['z'].offset
    step = msg.point_step
    data = bytes(msg.data)
    n = msg.width * msg.height
    pts = []
    for i in range(0, n, stride):
        base = i * step
        if base + oz + 4 > len(data):
            break
        x = struct.unpack_from('<f', data, base + ox)[0]
        y = struct.unpack_from('<f', data, base + oy)[0]
        z = struct.unpack_from('<f', data, base + oz)[0]
        if math.isfinite(x) and math.isfinite(y) and math.isfinite(z):
            pts.append((x, y, z))
        if len(pts) >= max_n:
            break
    return np.asarray(pts, dtype=np.float64)


def ransac_plane(pts, iters=600, thr=0.05):
    if pts.shape[0] < 80:
        return None
    best = None
    best_c = 0
    n = pts.shape[0]
    rng = np.random.default_rng(0)
    for _ in range(iters):
        i0, i1, i2 = rng.choice(n, 3, replace=False)
        p0, p1, p2 = pts[i0], pts[i1], pts[i2]
        nrm = np.cross(p1 - p0, p2 - p0)
        ln = np.linalg.norm(nrm)
        if ln < 1e-9:
            continue
        nrm = nrm / ln
        if nrm[2] < 0:
            nrm = -nrm
        d = -float(nrm @ p0)
        c = int(np.sum(np.abs(pts @ nrm + d) <= thr))
        if c > best_c:
            best_c = c
            best = (nrm, d, c)
    return best


def up_to_pitch_roll(up):
    """Unit up → pitch_down (>0 looks down), roll (rad). Matches v2 convention."""
    u = up / (np.linalg.norm(up) or 1.0)
    pitch = math.atan2(-u[0], math.hypot(u[1], u[2]))
    roll = math.atan2(u[1], u[2]) if abs(math.cos(pitch)) > 1e-6 else 0.0
    return pitch, roll


class CalibNode(Node):
    def __init__(self, imu_topic, cloud_topic):
        super().__init__('calib_lidar_imu_gravity')
        self.accs = []
        self.cloud_pts = []
        self.create_subscription(Imu, imu_topic, self.on_imu, qos_profile_sensor_data)
        if cloud_topic:
            self.create_subscription(
                PointCloud2, cloud_topic, self.on_cloud, qos_profile_sensor_data)
        self.get_logger().info(f'imu={imu_topic} cloud={cloud_topic or "-"}')

    def on_imu(self, msg: Imu):
        a = np.array([
            msg.linear_acceleration.x,
            msg.linear_acceleration.y,
            msg.linear_acceleration.z], dtype=np.float64)
        m = float(np.linalg.norm(a))
        if not math.isfinite(m) or m < 1e-3:
            return
        # Accept ~9.8 m/s^2 or ~1 g units; reject hard motion
        ok = (7.0 < m < 12.5) or (0.7 < m < 1.35)
        if not ok:
            return
        self.accs.append(a / m)

    def on_cloud(self, msg: PointCloud2):
        pts = unpack_xyz(msg)
        if pts.shape[0]:
            self.cloud_pts.append(pts)


def write_yaml(path, pitch_down, roll, lidar_z, meta):
    os.makedirs(os.path.dirname(path) or '.', exist_ok=True)
    with open(path, 'w') as f:
        f.write('# Auto-generated by calib_lidar_imu_gravity.py\n')
        f.write(f'pitch_down: {pitch_down:.6f}\n')
        f.write(f'pitch_down_deg: {math.degrees(pitch_down):.3f}\n')
        f.write(f'roll: {roll:.6f}\n')
        f.write(f'roll_deg: {math.degrees(roll):.3f}\n')
        f.write(f'lidar_z: {lidar_z:.4f}\n')
        f.write(f'lidar_pitch: {-pitch_down:.6f}\n')
        f.write(f'lidar_roll: {roll:.6f}\n')
        for k, v in meta.items():
            f.write(f'# {k}: {v}\n')
    print('wrote', path)


def collect(imu_topic, cloud_topic, seconds):
    node = CalibNode(imu_topic, cloud_topic)
    t0 = time.time()
    while time.time() - t0 < seconds:
        rclpy.spin_once(node, timeout_sec=0.1)
    return node


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--seconds', type=float, default=8.0)
    ap.add_argument('--imu', default='/livox/imu')
    ap.add_argument('--imu-fallback', default='/imu/data_raw')
    ap.add_argument('--cloud', default='/livox/lidar')
    ap.add_argument('--out', default=OUT_DEFAULT)
    ap.add_argument('--apply', action='store_true')
    ap.add_argument('--lidar-z', type=float, default=0.45)
    args = ap.parse_args()

    rclpy.init()
    print(f'Stand still on flat ground… collecting {args.seconds:.0f}s')
    node = collect(args.imu, args.cloud, args.seconds)
    if len(node.accs) < 20:
        print(f'Few samples on {args.imu} ({len(node.accs)}), trying {args.imu_fallback}')
        node.destroy_node()
        node = collect(args.imu_fallback, args.cloud, args.seconds)

    if len(node.accs) < 20:
        print('ERROR: not enough IMU samples')
        node.destroy_node()
        rclpy.shutdown()
        sys.exit(2)

    A = np.stack(node.accs, axis=0)
    segs = [s for s in np.array_split(A, 5) if len(s)]
    segs_u = [(s.mean(0)) for s in segs]
    segs_u = [u / (np.linalg.norm(u) or 1) for u in segs_u]
    # REP-145: a stationary IMU reports specific force ≈ +g pointing UP
    # (reaction to gravity), so "up" in the sensor frame is +mean(accel),
    # not -mean(accel). (Verified against this robot's live IMU: the old
    # negated formula produced roll≈180° and pitch_down≈-46.6°, exactly
    # the sign-flipped mirror of the expected ≈+45°/0° mount geometry.)
    up = (A.mean(0))
    up = up / (np.linalg.norm(up) or 1.0)
    pitch, roll = up_to_pitch_roll(up)
    pitches = [up_to_pitch_roll(u)[0] for u in segs_u]
    spread = (max(pitches) - min(pitches)) * 180 / math.pi if pitches else 0.0

    print('--- IMU gravity ---')
    print(f'  samples: {len(node.accs)}')
    print(f'  up: ({up[0]:+.4f}, {up[1]:+.4f}, {up[2]:+.4f})')
    print(f'  pitch_down: {math.degrees(pitch):.2f}° ({pitch:.4f} rad)')
    print(f'  roll:       {math.degrees(roll):.2f}° ({roll:.4f} rad)')
    print(f'  5-seg pitch spread: ±{spread:.3f}°')
    print(f'  ROS lidar_pitch: {-pitch:.6f}')

    cloud_pitch = cloud_roll = fitted_z = None
    if node.cloud_pts:
        pts = np.concatenate(node.cloud_pts, axis=0)
        h = pts @ up
        low = pts[(h > -2.5) & (h < 0.25)]
        print(f'--- RANSAC cloud ({pts.shape[0]} pts, low={low.shape[0]}) ---')
        fit = ransac_plane(low) if low.shape[0] > 100 else None
        if fit:
            nrm, d, c = fit
            if float(nrm @ up) < 0:
                nrm, d = -nrm, -d
            cloud_pitch, cloud_roll = up_to_pitch_roll(nrm)
            fitted_z = abs(d)
            diff = abs(math.degrees(pitch - cloud_pitch))
            print(f'  inliers={c}  pitch={math.degrees(cloud_pitch):.2f}°  '
                  f'roll={math.degrees(cloud_roll):.2f}°  z≈{fitted_z:.3f}m')
            print(f'  |IMU−RANSAC| pitch: {diff:.2f}°')
        else:
            print('  RANSAC failed')

    use_pitch, use_roll, src = pitch, roll, 'imu'
    if cloud_pitch is not None and abs(pitch - cloud_pitch) < math.radians(1.5):
        use_pitch, use_roll, src = cloud_pitch, cloud_roll, 'ransac'
        print('  → prefer RANSAC (diff < 1.5°)')
    else:
        print('  → prefer IMU')

    lidar_z = fitted_z if fitted_z is not None else args.lidar_z
    meta = {'imu_samples': len(node.accs), 'pitch_spread_deg': f'{spread:.4f}', 'source': src}
    if args.apply:
        write_yaml(args.out, use_pitch, use_roll, lidar_z, meta)
    else:
        print('(dry-run; pass --apply to write)')
        print(f'would write pitch_down={use_pitch:.6f} roll={use_roll:.6f} z={lidar_z:.3f} → {args.out}')

    node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
